server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/catalog_db?authSource=admin
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
