image:
  repository: pizzaflow/delivery-service
  tag: latest

service:
  type: ClusterIP
  port: 8088

env:
  SPRING_PROFILES_ACTIVE: "prod"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-service:8761/eureka/"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-service:8888/"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/delivery_db"
  SPRING_DATASOURCE_USERNAME: "postgres"
secretEnv:
  SPRING_DATASOURCE_PASSWORD:
    secretName: pizzaflow-infra-secrets
    secretKey: postgres-password

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
