FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
COPY services/kitchen-service/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
