/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderItemDto } from './orderItemDto';
import type { Address } from './address';

export interface CreateOrderRequest {
  customerId: string;
  /** @minItems 1 */
  items?: OrderItemDto[];
  deliveryAddress?: Address;
  longitude?: number;
  latitude?: number;
}
