/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface OrderItemDto {
  /** @minLength 1 */
  productId?: string;
  /** @minimum 1 */
  quantity?: number;
  /** @minimum 0.01 */
  unitPrice?: number;
}
