/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateInventoryItemRequest {
  productId: string;
  productName: string;
  /** @minimum 0 */
  quantity: number;
  unit: string;
}
