apiVersion: v1
kind: Secret
metadata:
  name: pizzaflow-infra-secrets
  namespace: pizzaflow
type: Opaque
stringData:
  postgres-password: password
  mongo-password: password
  keycloak-admin-password: admin
  keycloak-db-password: password
  grafana-admin-password: admin
